# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
 version: 2
 jobs:
   one:
     docker:
      - image: circleci/php:7.1-node-browsers
     steps:
       - checkout
       - run: echo "Hello"
       - run: sleep 25
   two:
     docker:
      - image: circleci/php:7.1-node-browsers
     steps:
       - checkout
       - run: echo "Hii"
       - run: sleep 15
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
